### ISSUE TITLE
[FRONT] URL is not updated on change

### ISSUE THREAD

**Issue by nriss** [arkhn/warehouse-api#142]
## Description
Front api url is not refreshed in cache when we use copy/paste or select / delete.
It is only refreshed when using the select box of search param or writing by hand on inputs 

## Reproduction

1. Copy (base)/CarePlan?date=eq2020-09-12
2. select ?date=eq2020-09-12 and delete

## Expectation

Modification of the url with copy/paste or select/delete must be taken into account

## Environment

In staging

## Resolution

The AutoComplete is already listened by an OnChange event (https://github.com/arkhn/warehouse-api/blob/master/front/src/components/search/index.tsx line 170)

I think the solution is to add `inputValue={fhirUrl}` to the autocomplete form 
see : https://material-ui.com/components/autocomplete/#controllable-states

**Comment by simonvadee** [comment]
fixed by arkhn/warehouse-api#143
