### ISSUE TITLE
Search with an empty string returns API internal error

### ISSUE THREAD

**Issue by BPierrick** [arkhn/warehouse-api#145]
## Description
Searching a resource with a parameter with an empty string as a value returns an error 500

## Reproduction
1. Go to front-api
2. Select a resource (like patient)
3. Select a search parameter (like identifier)
4. Set its value to an empty string (or with a space) like ' '
5. Execute the request

## Expectation
Getting an empty resource list as a result

## Screenshots
![Capture d’écran 2020-09-29 à 18 24 22](https://user-images.githubusercontent.com/12270309/94586054-13228c00-0281-11eb-9a15-35ccf3115699.png)

## Environment
Staging

**Comment by simonvadee** [comment]
Fixed this in https://github.com/nazrulworld/fhirpath/pull/21

But BEWARE: the FHIR spec says that empty parameters should be ignored, so the query `Patient?_id=` will return the list of all patients!
