### ISSUE TITLE
ACL specification

### ISSUE THREAD

**Issue by simonvadee** [arkhn/warehouse-api#19]
Specify how ACL are supposed to work:
- how granular should the system be
- how do we link an identity to a request (authentication)
- figure out what techno can we use to have efficient and granular acl

(linked to https://github.com/arkhn/warehouse-api/issues/20)

**Comment by Nabellaleen** [comment]
Could you list examples of the needs these ACLs should cover ?

**Comment by simonvadee** [comment]
No I can't just yet, I know the customers started talking about ACL with corneliu and emeric but I don't know what their needs are. I think it should be part of this specification to define specific ACL use cases, but here's a few thoughts:

- A FHIR resource may be read or write restricted to some type of account (eg: the doctor is allowed to access the patient medical file, but not someone working at the hospital's administration)
- A FHIR resource may be scoped to a specific unit of the hospital and should not be accessible from someone outside of this unit.

**Comment by simonvadee** [comment]
too vague
