### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by simonvadee** [arkhn/warehouse-api#20]
How do we manage identity in fhir-api ?

- do we develop our own identity system  ? (= users have login/password)
- do we integrate with a custom in-house system ? (LDAP, kerberos...)
- do we use external OAuth identity providers ? (google etc...)

- how do we implement single sign-on (SSO) ==> authenticate only once and have access to multiple services.

(Linked to https://github.com/arkhn/warehouse-api/issues/19)

**Comment by Nabellaleen** [comment]
Could you list the various cases where an authorization/authentication is needed ?

Also pay attention to the differences between an account and a user, it can help you to model all this stuff.

**Comment by simonvadee** [comment]
for authorization, see #19 

as for authentication, I think that pretty soon we will need to restrict access to the API to authenticated users, which requires some kind of authentication mechanism.

I fully agree with the user/account distinction, and I already modeled such a system at my previous company which had similar requirements.
