### ISSUE TITLE
Implement fhir compliant paging in API

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/warehouse-api#29]

**Comment by simonvadee** [comment]
First version should be simple: offset and limit without joins.

**Comment by vmttn** [comment]
Can you link to the fhir spec on paging ?

**Comment by elsiehoffet-94** [comment]
See [paging](https://www.hl7.org/fhir/http.html#paging) and [count](https://www.hl7.org/fhir/search.html#count)
